ALTER TABLE ai_settings ADD COLUMN IF NOT EXISTS allow_clarification BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE ai_settings ADD COLUMN IF NOT EXISTS max_clarification_count INTEGER NOT NULL DEFAULT 1;
ALTER TABLE ai_settings ADD COLUMN IF NOT EXISTS require_action_confirmation BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE ai_settings ADD COLUMN IF NOT EXISTS escalate_low_confidence BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE ai_settings ADD COLUMN IF NOT EXISTS guide_next_step BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE ai_settings ADD COLUMN IF NOT EXISTS concise_response BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE ai_agents ADD COLUMN IF NOT EXISTS allow_clarification BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE ai_agents ADD COLUMN IF NOT EXISTS max_clarification_count INTEGER NOT NULL DEFAULT 1;
ALTER TABLE ai_agents ADD COLUMN IF NOT EXISTS require_action_confirmation BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE ai_agents ADD COLUMN IF NOT EXISTS escalate_low_confidence BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE ai_agents ADD COLUMN IF NOT EXISTS guide_next_step BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE ai_agents ADD COLUMN IF NOT EXISTS concise_response BOOLEAN NOT NULL DEFAULT TRUE;
